version: "3.8"

services:
  fastapi:
    container_name: fastapi
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - ${GRAPH_CACHE_DIR}:/graph_cache
    expose:
      - ${FASTAPI_PORT}

  nginx_proxy:
    container_name: nginx_proxy
    image: nginx:1.23-alpine
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    # lamma change to 80
      - 8500:8500
    depends_on:
      - fastapi
